# Commands to run after login and AeroSpace startup
after-login-command = []
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Size of padding to indicate other applications available in that direction
accordion-padding = 30

# Default layout
default-root-container-layout = 'tiles'

# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes disabled
on-focused-monitor-changed = []

# Effectively disable macOS "Hide application" (cmd-h) feature
automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
[gaps]
inner.horizontal = 4
inner.vertical =   4
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[mode.main.binding]
# Keybinds to start applications
alt-enter = 'exec-and-forget open -na Kitty'
alt-w = 'exec-and-forget open -na Firefox'
alt-e = '''exec-and-forget osascript -e '
tell application "Finder"
    activate
    set home_path to (path to home folder as text)
    make new Finder window to home_path
end tell'
'''

# Toggle layouts
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# Toggle fullscreen
alt-f = 'fullscreen'

# Toggle floating
alt-shift-f = 'layout floating tiling'

# Move focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move node
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-ctrl-shift-h = ['join-with left', 'mode main']
alt-ctrl-shift-j = ['join-with down', 'mode main']
alt-ctrl-shift-k = ['join-with up', 'mode main']
alt-ctrl-shift-l = ['join-with right', 'mode main']

# Move focus to workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

# Move node to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

# Focus monitor
alt-x = 'focus-monitor left'
alt-c = 'focus-monitor right'

# Move workspace to monitor
alt-shift-x = 'move-workspace-to-monitor prev'
alt-shift-c = 'move-workspace-to-monitor next'

# Change to most recently used workspace
alt-tab = 'workspace-back-and-forth'

# Change modes
alt-shift-semicolon = 'mode service'
alt-r = 'mode resize'

[mode.service.binding]
esc = 'mode main'

# Reload config
c = ['reload-config', 'mode main']

# Reset layout
r = ['flatten-workspace-tree', 'mode main']

[mode.resize.binding]
esc = 'mode main'
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'

